apiVersion: v1
kind: Service
metadata:
  name: devpi
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80
  selector:
    app: devpi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: devpi
spec:
  template:
    metadata:
      labels:
        app: devpi
    spec:
      volumes:
        - name: data
          emptyDir: {}
        - name: nginx-htpasswd
          secret:
            secretName: nginx-htpasswd
      containers:
      - name: devpi
        image: arthurk/docker-devpi
        ports:
        - containerPort: 3141
        volumeMounts:
        - mountPath: /data
          name: data
      - name: devpi-nginx
        image: arthurk/devpi-nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: secret-volume
          mountPath: /etc/nginx-htpasswd
          readOnly: true
