apiVersion: v1
kind: ReplicationController
metadata:
  name: devpi
spec:
  template:
    metadata:
      labels:
        app: devpi
    spec:
      containers:
      - name: devpi
        image: arthurk/docker-devpi
        volumeMounts:
        - mountPath: /data
          name: devpi-data
        ports:
        - containerPort: 3141
      volumes:
        - name: devpi-data
          hostPath:
            path: /data
