version: '2'
services:
  devpi:
    build: .
    volumes:
      - ./data:/data
    ports:
      - "3141:3141"
    environment:
      - DEVPI_ROOT_PASSWORD=test
      - DEVPI_USER=test
      - DEVPI_PASSWORD=test
      - DEVPI_INDEX=dev
